### ISSUE TITLE
Support tuple validation in jsonschema arrays

### ISSUE THREAD

**Issue by acmiyaguchi** [mozilla/jsonschema-transpiler#38]
In mps:
https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/63028f589c9819f03c0c71d642517f0f22953cb5/validation/pocket/fire-tv-events.1.sample.pass.json#L12-L17

is validated by this:

https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/63028f589c9819f03c0c71d642517f0f22953cb5/schemas/pocket/fire-tv-events/fire-tv-events.1.schema.json#L10-L50

This currently generates the following error:
`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: sequence, expected struct Tag", line: 0, column: 0)', src/libcore/result.rs:1009:5`

See: https://json-schema.org/understanding-json-schema/reference/array.html#tuple-validation

**Comment by acmiyaguchi** [comment]
Fixed in #37, it will almost always be casted into JSON.

**Comment by acmiyaguchi** [comment]
While this is no longer immediately broken, it should be supported properly as either an anonymous struct (`_0`, `_1`, `_2`, etc based on the min/max number of fields), or a regular struct with a single list item. The latter will require coordination from the decoding piece in [mozilla/gcp-ingestion](https://github.com/mozilla/gcp-ingestion).

**Comment by relud** [comment]
> an anonymous struct (_0, _1, _2, etc based on the min/max number of fields)

if we do this we should follow the field naming that BigQuery uses for anonymous structs (`_f0`, `_f1`, `_f2`, etc)

> or a regular struct with a single list item

As discussed in the team meeting today, we could use a `oneOf` condition to specify a struct alongside tuples, providing both an upgrade path and the necessary info to coerce tuples to structs.

**Comment by acmiyaguchi** [comment]
> As discussed in the team meeting today, we could use a `oneOf` condition to specify a struct alongside tuples, providing both an upgrade path and the necessary info to coerce tuples to structs.

This is a nice solution. It seems like there should be some idea of precedence among the different types, such as the `Union[Tuple, Object]` or `Union[Tuple, String]`. This should be handled by `ast::Union::collapse`: 

https://github.com/mozilla/jsonschema-transpiler/blob/536c6fd9fb9095b91bb92fca17bd80927eceb873/src/ast.rs#L91-L98

I'm a bit wary of adding too much custom logic into the encoder, but this seems like it strikes a good balance.

**Comment by jklukas** [comment]
> if we do this we should follow the field naming that BigQuery uses for anonymous structs (_f0, _f1, _f2, etc)

If we do this, we could still support nice naming for event-type fields at the view layer. So for the event ping, the `telemetry.events` view would replace the `_f0`, etc. names with more descriptive variants.
