### ISSUE TITLE
Convert camel case bigquery column names to snake case

### ISSUE THREAD

**Issue by jklukas** [mozilla/jsonschema-transpiler#77]
See https://github.com/mozilla/gcp-ingestion/issues/671

The direct to parquet datasets coerce camel case keys to snake case, but right now our pipeline of pings into bigquery does not.

I think this consistent naming would be desirable and it would be best/simplest to handle it in the pipeline rather than deferring to views. This would require a coordinate change in the schema transpiler and in the BigQuery sink dataflow jobs.

**Comment by acmiyaguchi** [comment]
This is another backwards incompatible change, we should be prepared to drop data at the end of it. Here is where we currently modify properties to satisfy BigQuery column naming:

https://github.com/mozilla/jsonschema-transpiler/blob/a532e90cb7734ce5aa94fa3aa3e7eeebbd1fb935/src/ast.rs#L450-L464

**Comment by jklukas** [comment]
> This is another backwards incompatible change, we should be prepared to drop data at the end of it.

Yes, I want to roll together any remaining disruptive changes in the next few weeks so that we can deploy reliable prod stacks. In particular, I'd love to roll this together with deploying a final main ping schema representation.

**Comment by relud** [comment]
in direct2parquet we did snake case partially because of the issues with camel case described here: https://docs.aws.amazon.com/athena/latest/ug/tables-databases-columns-names.html

**Comment by jklukas** [comment]
We discussed this in the data platform team meeting today, and there was a question as to where this should happen in the pipeline. The choices are:

1. Transform in the Decoder immediately after validating the payload using the JSON schema, meaning that the decoded streams in PubSub also have snake_case normalized payloads
1. Transform in the BigQuery sink
1. Transform in BigQuery via a view generated from the schema

I worry that trying to handle this in a BigQuery view won't be tenable. It's potentially a very large amount of query text for the view, which could introduce performance issues.

**Comment by relud** [comment]
> It's potentially a very large amount of query text for the view, which could introduce performance issues.

also could be an issue with [`Maximum unresolved standard SQL query length — 1 MB`](https://cloud.google.com/bigquery/quotas#query_jobs)

**Comment by jklukas** [comment]
See proposal document: https://docs.google.com/document/d/1lY0yGiC8Okx0eJAzI_Pik3-kW4CgNBN2OhMLHlM_uLQ/edit#heading=h.5x0d5h95i329

**Comment by jklukas** [comment]
The snake casing document is closing today. After some refactoring about where we apply snake casing, we are still planning to use snake case in BQ, so this change is needed.

**Comment by jklukas** [comment]
@acmiyaguchi is going to work on this early next week.
